### ISSUE TITLE
iOS 8 hide with animation.

### ISSUE THREAD

**Issue by dranca** [wicharek/UINavigationBar-FixedHeightWhenStatusBarHidden#2]
I tried on the main project but i was not able to made this work. The problem is with navigation bar moving up / down when showing / hiding the status bar. 

I made a test project https://github.com/dranca/MenuNavigationTest. Is it just me? I worked on iOS 8.3 build.

**Comment by wicharek** [comment]
Indeed there is a small glitch on iOS 8 when you show/hide status bar like in your example. Can't find a quick fix. It will most probably require hacking more deeply into view hierarchy. Do you need status bar showing/hiding like in your example in real life project?

**Comment by dranca** [comment]
Apparently if i hide the navigation bar without the animation, this will not happen. Do you have any suggestions to mimic the hiding / showing of the status bar ?

**Comment by cbttpaul** [comment]
Any update on a solution to this issue? It is still present in iOS 9.

**Comment by wicharek** [comment]
At time I couldn't find a quick solution for this issue. Had some time to revisit it lately. Apparently animation works fine on iOS 10+. Since we have iOS 11, I'll leave it as is. My suggestion to anyone who might need - just do not use animation on iOS <= 9 if you have to support those OS versions.
