### ISSUE TITLE
iOS11 not work

### ISSUE THREAD

**Issue by czwpro** [wicharek/UINavigationBar-FixedHeightWhenStatusBarHidden#3]

**Comment by ajitam** [comment]
+1

**Comment by alsantos123** [comment]
+1

**Comment by wicharek** [comment]
Hey, iOS 11 should be working in just pushed version 1.1.0. Note that for iOS 11 you will also have to set `additionalSafeAreaInsets` on all affected view controllers. Otherwise view controller's content will "jump" up as if navigation bar has the regular height. See README for more details.

Let me know if it works for you. Thanks!

P.S. Now also available in CocoaPods
